name: docker-mirror-branches
on:
  - push
  - workflow_dispatch
env:
  version: latest
jobs:
  product:
    name: product
    runs-on: arm64
    outputs:
      product: ${{ steps.config.outputs.product }}
    steps:
      - uses: actions/checkout@v4
      - name: dagger=0.11.8
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.11.8 sh
      - name: dagger=product
        id: config
        run: |
          # write your own scoped version of the following since  is not available at this base level
          # echo product=$(./bin/dagger -m  call product-json --src=. --version=${{ env.version }}) >> $GITHUB_OUTPUT
          echo product=$(./bin/dagger -m github.com/bradfordwagner/dagger-modules/container_mirror@feature/ansible call product-json --src=. --version=${version}) >> $GITHUB_OUTPUT
  builds:
    runs-on: ${{ matrix.product.runner }}
    permissions: write-all
    needs: product
    name: ${{ matrix.product.index }}:${{ matrix.product.repo }}-${{ matrix.product.tag }} (${{ matrix.product.arch }})
    strategy:
      fail-fast: false
      matrix:
        product: ${{ fromJSON(needs.product.outputs.product) }}
    steps:
      - uses: actions/checkout@v4
      - name: dagger=0.11.8
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.11.8 sh
      
      # work around other runner's logging out removing credentials
      # https://github.com/docker/login-action/issues/173#issuecomment-1079688020
      - name: Set DOCKER_CONFIG
        run: |
          id=docker_configs/$(uuidgen)
          mkdir -p $HOME/${id}/.docker
          echo "DOCKER_CONFIG=$HOME/${id}/.docker" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          logout: false
      - name: dagger=build
        id: config
        run: |
          ./bin/dagger -m github.com/bradfordwagner/dagger-modules/container_mirror@feature/ansible call build \
            --src=. \
            --index=${{ matrix.product.index }} \
            --version=${version} \
            --isDev=false
  manifest:
    runs-on: arm64
    permissions: write-all
    needs: builds
    name: manifest-tool
    env:
      actor: ${{ github.actor }}
      token: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: dagger=0.11.8
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.11.8 sh
      # work around other runner's logging out removing credentials
      # https://github.com/docker/login-action/issues/173#issuecomment-1079688020
      - name: Set DOCKER_CONFIG
        run: |
          id=docker_configs/$(uuidgen)
          mkdir -p $HOME/${id}/.docker
          echo "DOCKER_CONFIG=$HOME/${id}/.docker" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          logout: false
      - name: dagger=manifest
        id: config
        run: |
          ./bin/dagger -m github.com/bradfordwagner/dagger-modules/container_mirror@feature/ansible call manifest \
            --src=. \
            --version=${version} \
            --actor=env:actor \
            --token=env:token
